MyCoreWebApp/Controllers/CustomerController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MyCoreWebApp.Models.DataModels;
using Bogus;
using MyCoreWebApp.Models;
using System.Diagnostics;

namespace MyCoreWebApp.Controllers
{
    public class CustomerController : Controller
    {

        public IActionResult Index()
        {

            var model = new List<CustomerDataModel>();
            //create a list of people using bogus assign the person to our customers class
            for (int i = 0; i <= 15; i++)
            {
                //new person created each loop
                var person = new Person();
                model.Add(new CustomerDataModel { customerId = i, customerFirstName = person.FirstName, customerLastName = person.LastName, customerUserName = person.UserName, Email = person.Email });

            }
            //Create random content for filling the page
            ViewData["Message"] = new Faker().Lorem.Paragraph().ToString();

            //return model back to the view
            return View("Index", model);
        }

        public ActionResult Details(int id)
        {
            //check the id got passed in
            if (id >= 0)
            {
                //new person created 
                var person = new Person();

                return View("Details", new CustomerDataModel { customerId = id, customerAvatar = person.Avatar, customerFirstName = person.FirstName, customerLastName = person.LastName, customerUserName = person.UserName, Email = person.Email });
            }
            else
            {
                return Error();
            }

        }
        public ActionResult Error()
        {
            return View("Error", new ErrorViewModel { Message = "Sorry the customer you're looking for could not be found.", RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    
        public ActionResult Create()
        {
            CustomerDataModel customer = new CustomerDataModel();
            ViewData["Message"] = new Faker().Lorem.Paragraph().ToString();
            customer.customerId = GeneratePersonId();

            //pass value from model into the view
            return View(customer);
        }

        //ref - https://github.com/bchavez/Bogus#without-fluent-syntax
        //Get a random toload as a new user's id. 
        public int GeneratePersonId()
        {
            var random = new Randomizer();
            return random.Number(1, 1000);
        }
        [HttpPost]
        public ActionResult Create(CustomerDataModel customer)
        {

            return View("Index");
        }
    }
}

MyCoreWebApp/Controllers/ServiceRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyCoreWebApp.Models;
using MyCoreWebApp.Models.DataModels;
//Used for customers to submit work orders
namespace MyCoreWebApp.Controllers
{
    public class ServiceRequestController : Controller
    {
        

        //TODO: create form post of the create method to capture user input. 
        [HttpGet]
        public IActionResult Create()
        {
            //Instantiate model to generate request list
            var model = new ServiceRequestDataModel();

            //Getting todays current date
            DateTime CurrentTime = DateTime.Now;
            
            model.IdealRequestDate = CurrentTime.AddDays(3);

            //view name, object model
            return View("Create",model);
        }

        public IActionResult Create2(string ServiceDescription, int RequestTypeId, string RequestName, string Email, bool CustomerConsent, string RequestType)
        {
            //Instantiate model to generate request list
            var model = new ServiceRequestViewModel();

            model.ServiceDescription = ServiceDescription;
            model.Email = Email;
            model.CheckBox = CustomerConsent;
            model.Id = RequestTypeId;
            model.Name = RequestName;
            model.RequestType = RequestType;


            //1. First get the list of possible request options a customer can select from
           IEnumerable<string> Mylist = GetServiceRequestOptions();

            //2. Bind the list to the model 
            model.RequestTypeDdl = CreateSelectList(Mylist);

            
            return RedirectToAction("Create", model);
        }

        // Add Service Request options here if needed
        private IEnumerable<string> GetServiceRequestOptions()
        {
            return new List<string>
            {
                "General Checkup",
                "Maintenance / Repair",
                "Cleaning",
                "Equipment",
                "Tank Modfication",
                "Other"               
            };
        }


        // This is one of the most important parts in the whole example.
        // This function takes a list of strings and returns a list of SelectListItem objects.
        // These objects are going to be used later in the SignUp.html template to render the
        // DropDownList.
        private IEnumerable<SelectListItem> CreateSelectList(IEnumerable<string> elements)
        {
            // Create an empty list to hold result of the operation
            List<SelectListItem> selectList = new List<SelectListItem>();

            // For each string in the 'elements' variable, create a new SelectListItem object
            // that has both its Value and Text properties set to a particular value.
            // This will result in MVC rendering each item as:
            //     <option value="Request Type">Request Type Name</option>
            foreach (var element in elements)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element,
                    Text = element
                });
            }

            return selectList;
        }
    }
}

MyCoreWebApp/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="row">
    <div class="col-md-12">
        <p class="text-center">&copy; @DateTime.Now.Year.ToString() - Dirty Fish Tank</p>
    </div>
    <br />
    <br />
    <br />
    <div class="col-md-3">
        Icons made by <a href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
    </div>
    <div class="col-md-3">
        Logo's created by <a href="https://logohub.io/" title="LogoHub">Logo Hub</a>
    </div>
    <div class="col-md-3">
        Navbar built with <a href="https://work.smarchal.com/twbscolor/" title="twbscolor">twbscolor</a>
    </div>
    <div class="col-md-3">
        Content from <a href="https://www.louisville-aquarium.com/aquarium-louisville-kentucky.html">Louisville Aquarium</a> as a proof of concept.
    </div>
</div>

MyCoreWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dirty Fish Tank</title>
   
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        <img alt="Brand" src="~/images/fishbadge.png">

                    </a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Dirty Fish Tank ?</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="GettingStarted">Get Started</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">Our Services</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <li><a asp-area="" asp-controller="Customer" asp-action="Index">Customers</a></li>
                        <li><a asp-area="" asp-controller="ServiceRequest" asp-action="Create">Submit A Service Request</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
   
    @RenderSection("Scripts", required: false)
</body>
</html>